### ISSUE TITLE
AttributeError: 'HMM' object has no attribute '_do_foward_pass' when calling HMM.fit()

### ISSUE THREAD

**Issue by AlineBornschein** [NorskRegnesentral/skweak#41] opened 2022-02-17 18:19 UTC
_do_forward_pass() seems to have been deprecated from new version of hmmlearn. After downgrading hmmlearn to version 0.2.6 the error is resolved.

**Comment by david-waterworth** [comment] 2022-03-01 01:53
I think this is a duplicate of https://github.com/NorskRegnesentral/skweak/issues/38

**Closed** 2022-03-24 23:58 UTC
